# Generated by Django 4.1.7 on 2023-04-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Travel", "Travel"),
                            ("Shopping", "Shopping"),
                            ("Necessities", "Necessities"),
                            ("Entertainment", "Entertainment"),
                            ("Fiverr", "Fiverr"),
                            ("Upwork", "Upwork"),
                            ("Salary", "Salary"),
                            ("Part-time", "Part-time"),
                            ("Other", "Other"),
                        ],
                        default="Food",
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={"db_table": "category",},
        ),
    ]
