# Generated by Django 4.1.7 on 2023-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_addmoney_info_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cat_type",
            field=models.CharField(
                choices=[("Expense", "Expense"), ("Income", "Income")],
                default="Expense",
                max_length=20,
            ),
        ),
    ]
