# Generated by Django 4.1.7 on 2023-04-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_category_cat_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="Food", max_length=20, unique=True),
        ),
    ]
